# Generated by Django 5.2.3 on 2025-06-18 21:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=25)),
                ('calle', models.CharField(max_length=200)),
                ('numero_interior', models.CharField(max_length=100)),
                ('numero_exterior', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=400)),
                ('responsable_email', models.EmailField(max_length=100)),
                ('responsable_telefono', models.CharField(max_length=25)),
                ('responsable_puesto', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizaciones', to='licence.licencia')),
            ],
            options={
                'verbose_name': 'Organizacion',
                'verbose_name_plural': 'Organizaciones',
                'db_table': 'organizacion',
                'ordering': ['nombre'],
            },
        ),
    ]
