# Generated by Django 5.2.3 on 2025-06-19 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoAlmacenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espacio_utilizado', models.PositiveBigIntegerField(default=0)),
                ('organizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.organizacion')),
            ],
            options={
                'verbose_name': 'Uso de Almacenamiento',
                'verbose_name_plural': 'Usos de Almacenamiento',
            },
        ),
    ]
