# Generated by Django 5.2.3 on 2025-06-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_usoalmacenamiento'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usoalmacenamiento',
            table='uso_almacenamiento',
        ),
    ]
