# Generated by Django 5.2.3 on 2025-06-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_usoalmacenamiento_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
