# Generated by Django 5.2.3 on 2025-06-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organizacion_inicio_organizacion_vencimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizacion',
            old_name='calle',
            new_name='titular',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='numero_exterior',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='numero_interior',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='responsable_email',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='responsable_puesto',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='responsable_telefono',
        ),
    ]
