# Generated by Django 5.2.3 on 2025-06-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_rename_calle_organizacion_titular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='membretado',
            field=models.ImageField(blank=True, null=True, upload_to='membretado/'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='membretado_2',
            field=models.ImageField(blank=True, null=True, upload_to='membretado/'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
