# Generated by Django 5.2.3 on 2025-06-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0001_initial'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='organizacion',
        ),
        migrations.RemoveField(
            model_name='record',
            name='pedimento',
        ),
        migrations.RemoveField(
            model_name='document',
            name='record',
        ),
        migrations.AddField(
            model_name='document',
            name='pedimento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customs.pedimento'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DocumentByRecord',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
