# Generated by Django 5.2.3 on 2025-06-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='descripcion',
        ),
    ]
