# Generated by Django 5.2.3 on 2025-06-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_remove_document_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='extension',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
