# Generated by Django 5.2.3 on 2025-06-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_documenttype_document_document_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documento'},
        ),
        migrations.RenameField(
            model_name='documenttype',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='documenttype',
            old_name='name',
            new_name='nombre',
        ),
    ]
