# Generated by Django 5.2.3 on 2025-06-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_alter_documenttype_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file',
            new_name='archivo',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='descripcion',
        ),
    ]
