# Generated by Django 5.2.3 on 2025-06-18 21:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aduana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Aduana',
                'verbose_name_plural': 'Aduanas',
                'db_table': 'aduana',
                'ordering': ['seccion'],
            },
        ),
        migrations.CreateModel(
            name='ClavePedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Clave de Pedimento',
                'verbose_name_plural': 'Claves de Pedimento',
                'db_table': 'clave_pedimento',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Patente',
                'verbose_name_plural': 'Patentes',
                'db_table': 'patente',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo de Operacion',
                'verbose_name_plural': 'Tipos de Operacion',
                'db_table': 'tipo_operacion',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='AgenteAduanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_aduana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentes_aduanales', to='customs.aduana')),
                ('id_patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentes_aduanales', to='customs.patente')),
            ],
            options={
                'verbose_name': 'Agente Aduanal',
                'verbose_name_plural': 'Agentes Aduanales',
                'db_table': 'agente_aduanal',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pedimento', models.CharField(max_length=20)),
                ('fechapago', models.DateField()),
                ('contribuyente', models.CharField(max_length=100)),
                ('alerta', models.BooleanField(default=False)),
                ('curp_apoderado', models.CharField(blank=True, max_length=18, null=True)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_disponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_pedimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('existe_expediente', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aduana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedimentos', to='customs.aduana')),
                ('agente_aduanal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedimentos', to='customs.agenteaduanal')),
                ('clave_pedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedimentos', to='customs.clavepedimento')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedimentos', to='organization.organizacion')),
                ('patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedimentos', to='customs.patente')),
                ('tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedimentos', to='customs.tipooperacion')),
            ],
            options={
                'verbose_name': 'Pedimento',
                'verbose_name_plural': 'Pedimentos',
                'db_table': 'pedimento',
                'ordering': ['pedimento'],
            },
        ),
    ]
